spring.application.name=recipe-backend

# URL de connexion à la base de données
spring.datasource.url=jdbc:mysql://localhost:3306/BNP-Project?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC

# Nom d’utilisateur MySQL
spring.datasource.username=root

# Mot de passe MySQL (ligne commenté par reda)
#spring.datasource.password=ton_mot_de_passe
spring.datasource.password=

# Pilote JDBC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Création/Mise à jour automatique des tables (create, update, validate, none)
spring.jpa.hibernate.ddl-auto=update

# Afficher les requêtes SQL dans la console
spring.jpa.show-sql=true

# Formater les requêtes SQL pour plus de lisibilité
spring.jpa.properties.hibernate.format_sql=true

spring.main.allow-bean-definition-overriding=true

#test reda
jwt.secret=MySuperSecretKey12345678909876543210123456789
jwt.expiration=3600000